allow samesite policy to be set on csrf cookie
pac4j/pac4j pull request #1811
Opened 2021-02-09 16:40 UTC by hdeadman

I was interested in being able to set samesite policy on the CSRF token (from CAS). This is adding support for that.

2021-02-09 19:01 UTC, leleuj requested changes
LGTM. One comment though.

2021-02-09 19:01 UTC, leleuj commented on pac4j-core/src/main/java/org/pac4j/core/context/JEEContext.java
>      public void addResponseCookie(final Cookie cookie) {
I guess this could be moved as a default implementation of the `addResponseCookie` method in the `WebContext` interface.

2021-02-09 19:27 UTC, hdeadman commented
I just saw your comment and will adjust, but I made an update b/c I noticed I wasn't using the comment version or expires attributes of the cookie. I removed some of those because they don't seem to be used much and I based Expires on the max-age, modeled after this: 
https://github.com/spring-projects/spring-framework/blob/c9b27af64f41cc4fd06ee41a0faaca867e3cba4e/spring-web/src/main/java/org/springframework/http/ResponseCookie.java#L155

The method for setting the cookie is sort of a combination of CAS and Spring cookie handling.

2021-02-09 20:11 UTC, hdeadman commented
I moved it to JEEContext rather than WebContext, because it needs the HTTP response object to really do anything useful, but I broke it up so that the method to create the String could be moved to WebContext, but it would be a static method ? Is there a utility class it could move to?

2021-02-10 01:41 UTC, hdeadman commented
I copied some logic from CAS where it sets the Secure attribute on the cookie if the same site policy is "none". 

https://github.com/apereo/cas/blob/3f2311323d60e279ad2834a506cd7eeaf8a5daca/core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/gen/CookieRetrievingCookieGenerator.java#L202

I don't know the rationale for that, but because the default same site policy in this PR is "none", the effect is that the cookie is set to "Secure" by default. That is probably not desirable and there is no way to turn off secure without changing the same site policy. Should the default be lax or should the logic copied from CAS be changed? 

I can make further updates or you are welcome to merge it and change it as you see fit. 

I added a couple tests. 

Thanks.

2021-02-10 12:32 UTC, leleuj commented
I think the `createCookieHeader` static method should be moved in the `ContextHelper` class (which should be renamed `WebContextHelper` to make things obvious).

2021-02-10 13:20 UTC, leleuj commented
About the default values, we can keep things like that. It is defined in the spec. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

2021-02-10 13:46 UTC, leleuj approved these changes

2021-02-10 13:46 UTC, merged

2021-02-10 13:56 UTC, hdeadman commented
I see you merged, thanks. Regarding the default samesite policy of None, since most browsers seem to be defaulting to Lax if nothing is set, would Lax be a better default since that is the effective policy that users of pac4j are getting now?

2021-02-10 14:03 UTC, leleuj commented
For this major version 5, we can break things, but as you said, if most browsers default to Lax, we should certainly do the same.