Ensure TokenCredentials are serializable to JSON
pac4j/pac4j pull request #2692
Opened 2023-10-04 20:13 UTC by hsartoris-bard

See also #2670.

Currently, the second test will fail unless additional typing information is introduced. Happy to tweak as needed.

2023-10-05 06:37 UTC, leleuj commented
Good. What's your fix proposal?

2023-10-10 14:32 UTC, hsartoris-bard commented
https://github.com/pac4j/pac4j/pull/2692/commits/c2cff70ad78995ffae92b448875529f52a644361 provides a fix for the first test, which otherwise fails.

https://github.com/pac4j/pac4j/pull/2692/commits/16d55922b2a424b9703152100e835024ca857fbd addresses the latter, by explicitly annotating `UserProfile` with `@JsonTypeInfo`. I also added `@EqualsAndHashCode` on `BasicUserProfile`, because otherwise equality checking on `TokenCredentials` doesn't work, but this is optional - I can either check that the tokens match between the original and the deserialized credentials, or set `callSuper` to false on TokenCredentials. My sense is that, semantically, it doesn't make sense to say that two TokenCredentials objects are equal simply if their tokens are equal, even if they contain differing UserProfiles.

2023-10-11 09:11 UTC, leleuj commented
Can you check why the build fails: https://github.com/pac4j/pac4j/actions/runs/6470734206/job/17595797077?pr=2692?

2023-10-11 13:14 UTC, hsartoris-bard commented
Ah yes, needed to also override `equals` on CasProxyProfile

2023-10-12 05:25 UTC, leleuj commented
The build still fails: `Error:  Medium: org.pac4j.kerberos.profile.KerberosProfile doesn't override org.pac4j.core.profile.BasicUserProfile.equals(Object) [org.pac4j.kerberos.profile.KerberosProfile] At KerberosProfile.java:[line 1] EQ_DOESNT_OVERRIDE_EQUALS`

2023-10-12 07:48 UTC, mmoayyed requested changes

2023-10-12 07:48 UTC, mmoayyed commented on pac4j-cas/src/main/java/org/pac4j/cas/profile/CasProxyProfile.java
> +@EqualsAndHashCode
Should this not be `@EqualsAndHashCode(callSuper = true)`?

2023-10-12 07:48 UTC, mmoayyed commented on pac4j-core/src/main/java/org/pac4j/core/profile/UserProfile.java
> +@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="class")
```suggestion
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "class")
```

2023-10-12 14:54 UTC, hsartoris-bard commented
good points; changes made. I was able to run the tests locally by excluding the SAML test suite, which appears to expect some service to be running that I do not have.

2023-10-13 07:20 UTC, leleuj commented
Can you sync with master? I have excluded two failing SAML tests.

2023-10-13 17:13 UTC, hsartoris-bard commented
Done; tests all pass for me now.

2023-10-16 12:30 UTC, merged